import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Sidebar from "@/components/Sidebar";
import Hamburger from "@/components/Hamburger";
import { Toaster } from "react-hot-toast";
import './posts.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mustafa Bhikhapurwala | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider defaultTheme="system" attribute="class">
        <Toaster/>
        <div className="flex h-screen overflow-hidden">

            {/* Sidebar */}
            <Sidebar />

            {/* Main content container */}
            <div className="flex flex-col flex-grow overflow-auto">
            <Hamburger/>
              
              {children}
            </div>

          </div>
        
          
        </ThemeProvider>
      </body>
    </html>
  );
}
